import joblib
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st
from datetime import time, timedelta
from skimage.measure import marching_cubes

# Page configuration
st.set_page_config(page_title="WorkTrack Log Predictor", layout="centered")

st.title("WorkTrack Log Predictor")

st.write("""
This project applies machine learning to a dataset of work time logs generated by the WorkTrack app 
(https://github.com/4l3b/WorkTrack). A polynomial logistic regression classifier was trained to predict whether a specific time of day 
is most likely to correspond to a clock in, break start, break end, or clock out event.
""")
st.write("Drag the time slider to see how the model predicts the log type in real-time.")

# Load the trained model
@st.cache_resource
def load_model():
    artifact = joblib.load('model.pkl')
    return artifact["model"], artifact["label_encoder"]

@st.cache_resource
def generate_decision_surface(_model, _le):

    hours = np.linspace(8, 19, 40)
    minutes = np.linspace(0, 59, 40)
    seconds = np.linspace(0, 59, 20)

    grid = np.array(
        np.meshgrid(hours, minutes, seconds, indexing="ij")
    ).reshape(3, -1).T

    grid_df = pd.DataFrame(
        grid,
        columns=["hour", "minute", "second"]
    )

    predictions = _model.predict(grid_df)

    volume = predictions.reshape(
        len(hours),
        len(minutes),
        len(seconds)
    )

    fig = go.Figure()

    colors = {
        "clockIn": "blue",
        "clockOut": "red",
        "breakStart": "green",
        "breakEnd": "purple"
    }


    for cls in np.unique(predictions):
    
        binary = (volume == cls).astype(float)
    
        if binary.min() == binary.max():
            continue
    
        try:
            verts, faces, _, _ = marching_cubes(
                binary,
                level=0.5
            )
        except ValueError:
            continue

        label = _le.inverse_transform([int(cls)])[0]

        fig.add_trace(
            go.Mesh3d(
                x=verts[:,0] * (hours[-1]-hours[0])/(len(hours)-1)+hours[0],
                y=verts[:,1] * (minutes[-1]-minutes[0])/(len(minutes)-1)+minutes[0],
                z=verts[:,2] * (seconds[-1]-seconds[0])/(len(seconds)-1)+seconds[0],

                i=faces[:,0],
                j=faces[:,1],
                k=faces[:,2],

                opacity=0.35,
                color=colors.get(label, "gray"),
                name=label,
                showlegend=True
            )
        )

    fig.add_trace(
        go.Scatter3d(
            x=[None],
            y=[None],
            z=[None],
            mode="markers",
            marker=dict(
                size=14,
                color="white",
                line=dict(
                    color="black",
                    width=2
                )
            ),
            name="Selected time",
            showlegend=True
        )
    )


    fig.update_layout(
        title="Classifier decision boundaries",
        scene=dict(
            xaxis_title="Hour",
            yaxis_title="Minute",
            zaxis_title="Second"
        ),
        height=700,
        legend=dict(
            title="Log type",
            x=0,
            y=1
        ),
        uirevision="constant"
    )

    return fig



try:
    model, le = load_model()

    left_col, right_col = st.columns([1, 2])

    with left_col:
    
        st.subheader("Time of the day:")
        
        # HH:MM slider restricted from 08:00 to 19:00
        user_time = st.slider(
            "Time of the day:",
            min_value=time(8, 0),
            max_value=time(19, 0),
            value=time(8, 0),
            step=timedelta(seconds=1),
            format="HH:mm:ss",
            label_visibility="collapsed"
        )
    
        # Convert selected time into model features
        hour = user_time.hour
        minute = user_time.minute
        second = user_time.second
        st.info(f"Model input features → Hour: {hour:02d} | Minute: {minute:02d} | Second: {second:02d}")
        input_data = pd.DataFrame([[hour, minute, second]], columns=["hour", "minute", "second"])
    
        # Real-time prediction
        raw_prediction = model.predict(input_data)[0]
        probabilities = model.predict_proba(input_data)[0]
        
        # Convert the numerical prediction to string
        readable_prediction = le.inverse_transform([raw_prediction])[0]
        
        # Display the final prediction output
        st.success(f"Predicted Log Type: {readable_prediction}")
        
        # Progress bars showing model confidence
        st.subheader("Model Confidence Level:")
        
        # Convert model class names into readable labels
        label_display_map = {
            "clockIn": "CLOCK IN",
            "clockOut": "CLOCK OUT",
            "breakStart": "BREAK START",
            "breakEnd": "BREAK END"
        }
        
        # Create a dictionary from the arrays for direct lookup
        prob_dict = {label_display_map.get(le.inverse_transform([int(c)])[0], "UNKNOWN"): p for c, p in zip(model.classes_, probabilities)}
        
        # Define a fixed order for the rows
        fixed_order = ["CLOCK IN", "BREAK START", "BREAK END", "CLOCK OUT"]
        
        for action in fixed_order:
            # Get the probability for the current action (default to 0.0 if not found)
            prob_val = prob_dict.get(action, 0.0)
            percentage = round(prob_val * 100, 1)
            
            # Display the text and the numerical percentage in a single clean row
            st.write(f"**{action}** ({percentage}%)")
    
            # Display the horizontal progress bar
            st.markdown(
                f"""
                <div style="
                    width: 100%; 
                    background-color: rgba(240, 242, 246); 
                    border-radius: 4px; 
                    height: 8px; 
                    margin-bottom: 20px;
                    overflow: hidden;
                ">
                    <div style="
                        width: {percentage}%; 
                        background-color: #3f82da; 
                        height: 100%; 
                        border-radius: 4px;
                        transition: width 0.3s ease-in-out;
                    "></div>
                </div>
                """,
                unsafe_allow_html=True
            )
    

    with right_col:

        st.subheader("Current position in the decision space")
        
        prediction_color = {
            "clockIn": "blue",
            "clockOut": "red",
            "breakStart": "green",
            "breakEnd": "purple",
            "CLOCK IN": "blue",
            "CLOCK OUT": "red",
            "BREAK START": "green",
            "BREAK END": "purple"
        }.get(readable_prediction, "black")
        
        fig = generate_decision_surface(model, le)
        point_trace = fig.data[-1]
        point_trace.marker.color = prediction_color
        
        point_trace.x = [hour]
        point_trace.y = [minute]
        point_trace.z = [second]
        
        
        st.plotly_chart(
            fig,
            use_container_width=True
        )





    # Copyright
    st.markdown(
        """
        <div style='text-align: center; margin-top: 4rem; font-size: 0.8rem; color: #777777;'>
            &copy; 2026 Alessandro Bigolin
        </div>
        """, 
        unsafe_allow_html=True
    )

except FileNotFoundError:
    st.error("File 'model.pkl' not found in the repository.")
