import streamlit as st
import pandas as pd
import joblib
import numpy as np
from datetime import time, timedelta

# Page configuration
st.set_page_config(page_title="WorkTrack Log Predictor", layout="centered")

st.title("WorkTrack Log Predictor")
st.write("""
This project applies machine learning to a dataset of work time logs generated by the WorkTrack app 
(https://4l3b.github.io/WorkTrack). A Stacking Ensemble classifier was trained to predict whether a specific time of day 
is most likely to correspond to a clock in, break start, break end, or clock out event.
""")
st.write("Drag the time slider to see how the Stacking Ensemble model predicts the log type in real-time.")

# Load the trained Stacking model
@st.cache_resource
def load_model():
    return joblib.load('stacking_model.pkl')

try:
    model = load_model()
    
    st.subheader("Time of the day:")
    
    # HH:MM slider restricted from 08:00 to 19:00
    user_time = st.slider(
        "Time of the day:",
        min_value=time(8, 0),
        max_value=time(19, 0),
        value=time(8, 0),
        step=timedelta(minutes=5),
        format="HH:mm",
        label_visibility="collapsed"
    )

    # Convert HH:MM back into seconds_from_midnight for X
    seconds_from_midnight = (user_time.hour * 3600) + (user_time.minute * 60)
    st.info(f"Feature value sent to the AI: {seconds_from_midnight} seconds elapsed since midnight.")

    # Create the input DataFrame for X
    input_data = pd.DataFrame([[seconds_from_midnight]], columns=['seconds_from_midnight'])

    # Real-time prediction
    raw_prediction = model.predict(input_data)[0] # Extract the numeric prediction (0, 1, 2, or 3)
    probabilities = model.predict_proba(input_data)[0]
    
    # Mapping dictionary to translate numbers into readable labels
    label_map = {
        0: "BREAK END",
        1: "BREAK START",
        2: "CLOCK IN",
        3: "CLOCK OUT"
    }
    
    # Convert the numerical prediction to string
    readable_prediction = label_map.get(int(raw_prediction), f"UNKNOWN (Class {raw_prediction})")
    
    # Map classes for the probability labels
    readable_classes = [label_map.get(int(c), f"Class {c}") for c in model.classes_]
    
    # Display the final prediction output
    st.success(f"Predicted Log Type: {readable_prediction}")
    
    # Progress bars showing model confidence
    st.subheader("Stacking Ensemble Confidence Level:")
    
    # Create a dictionary from the arrays for direct lookup
    prob_dict = {label_map.get(int(c), f"Class {c}"): p for c, p in zip(model.classes_, probabilities)}
    
    # Define a fixed order for the rows
    fixed_order = ["CLOCK IN", "BREAK START", "BREAK END", "CLOCK OUT"]
    
    for action in fixed_order:
        # Get the probability for the current action (default to 0.0 if not found)
        prob_val = prob_dict.get(action, 0.0)
        percentage = round(prob_val * 100, 1)
        
        # Display the text and the numerical percentage in a single clean row
        st.write(f"**{action}** ({percentage}%)")
        
        # Display the horizontal progress bar
        st.progress(float(prob_val))

    # Copyright
    st.markdown(
        """
        <div style='text-align: center; margin-top: 4rem; font-size: 0.8rem; color: #777777;'>
            &copy; 2026 Alessandro Bigolin
        </div>
        """, 
        unsafe_allow_html=True
    )

except FileNotFoundError:
    st.error("File 'stacking_model.pkl' not found in the repository.")
