import streamlit as st
import pandas as pd
import joblib
import numpy as np
from datetime import time, timedelta

# Page configuration
st.set_page_config(page_title="WorkTrack Log Predictor", layout="centered")

st.title("WorkTrack Log Predictor")

st.write("""
This project applies machine learning to a dataset of work time logs generated by the WorkTrack app 
(https://github.com/4l3b/WorkTrack). A polynomial logistic regression classifier was trained to predict whether a specific time of day 
is most likely to correspond to a clock in, break start, break end, or clock out event.
""")
st.write("Drag the time slider to see how the model predicts the log type in real-time.")

# Load the trained model
@st.cache_resource
def load_model():
    artifact = joblib.load('model.pkl')
    return artifact["model"], artifact["label_encoder"]

try:
    model, le = load_model()
    
    st.subheader("Time of the day:")
    
    # HH:MM slider restricted from 08:00 to 19:00
    user_time = st.slider(
        "Time of the day:",
        min_value=time(8, 0),
        max_value=time(19, 0),
        value=time(8, 0),
        step=timedelta(seconds=1),
        format="HH:mm:ss",
        label_visibility="collapsed"
    )

    # Convert selected time into model features
    hour = user_time.hour
    minute = user_time.minute
    second = user_time.second
    st.info(f"Model input features → Hour: {hour:02d} | Minute: {minute:02d} | Second: {second:02d}")
    input_data = pd.DataFrame([[hour, minute, second]], columns=["hour", "minute", "second"])

    # Real-time prediction
    raw_prediction = model.predict(input_data)[0]
    probabilities = model.predict_proba(input_data)[0]
    
    # Convert the numerical prediction to string
    readable_prediction = le.inverse_transform([raw_prediction])[0]
    
    # Display the final prediction output
    st.success(f"Predicted Log Type: {readable_prediction}")
    
    # Progress bars showing model confidence
    st.subheader("Model Confidence Level:")
    
    # Create a dictionary from the arrays for direct lookup
    prob_dict = {le.inverse_transform([int(c)])[0]: p for c, p in zip(model.classes_, probabilities)}
    
    # Define a fixed order for the rows
    fixed_order = ["CLOCK IN", "BREAK START", "BREAK END", "CLOCK OUT"]
    
    for action in fixed_order:
        # Get the probability for the current action (default to 0.0 if not found)
        prob_val = prob_dict.get(action, 0.0)
        percentage = round(prob_val * 100, 1)
        
        # Display the text and the numerical percentage in a single clean row
        st.write(f"**{action}** ({percentage}%)")

        # Display the horizontal progress bar
        st.markdown(
            f"""
            <div style="
                width: 100%; 
                background-color: rgba(240, 242, 246); 
                border-radius: 4px; 
                height: 8px; 
                margin-bottom: 20px;
                overflow: hidden;
            ">
                <div style="
                    width: {percentage}%; 
                    background-color: #3f82da; 
                    height: 100%; 
                    border-radius: 4px;
                    transition: width 0.3s ease-in-out;
                "></div>
            </div>
            """,
            unsafe_allow_html=True
        )

    # Copyright
    st.markdown(
        """
        <div style='text-align: center; margin-top: 4rem; font-size: 0.8rem; color: #777777;'>
            &copy; 2026 Alessandro Bigolin
        </div>
        """, 
        unsafe_allow_html=True
    )

except FileNotFoundError:
    st.error("File 'model.pkl' not found in the repository.")
